export const data = {
  about:
    "I am a detail-oriented, result-driven front-end developer with over 2 years of experience in building web applications. Equipped with a degree in computer science, my expertise lies in utilizing popular front-end frameworks and technologies such as React.js, Next.js, etc. I possess a strong understanding of object-oriented programming principles, allowing me to create responsive, feature-rich, and scalable interfaces for web applications.",
  skills: {
    languages: ["Javascript", "Typescript", "CSS", " SASS / SCSS"],
    tools: [
      "Gatsby Js",
      "Next Js",
      "React",
      // "Three Js",
      "GSAP",
      "Bootstrap",
      "Tailwind",
      "Framer Motion",
      "React Testing Library",
      "Git/Github",
      "Sanity.io",
    ],
    concepts: ["GraphQL", "Redux Toolkit", "RESTful APIs", "Context API"],
  },
  contact: {
    mail: "okogbofaith@gmail.com",
    linkedin: "https://www.linkedin.com/in/okogbo-faith",
    github: "https://github.com/faithandjs",
  },
  resume:
    "https://docs.google.com/document/d/1SGbJpa5e20i8mCoEKNFIejwr3G-fYzp3/edit?usp=sharing&ouid=116386074929625487222&rtpof=true&sd=true",
  projects: [
    {
      id: 1,
      name: "Zico Apartments",
      img: "zico.webp",
      tags: ["Sanity CMS", "Next Js", "GSAP", "Context API"],
      text: "Rental website that uses Sanity CMS as database.",
      live: "https://zicoapartments.com/",
      target: "_blank",
    },
    {
      id: 1,
      name: "Vivienne Daniels Store",
      img: "VD.webp",
      tags: [
        "SASS",
        "Gatsby JS",
        "shopify",
        "context API",
        "Paystack Integration",
      ],
      text: "Online shopping website I designed and developed. Users can browse products, add multiple quantities of different variants to cart, update their wishlist and checkout items.",
      github: "https://github.com/faithandjs/vivienne-daniels-store",
      live: "https://viviennedanielsstore.netlify.app/",
      target: "_blank",
    },
    {
      id: 2,
      name: "My Vision Board",
      img: "vision_board.webp",
      tags: ["SASS", "CSS Grid", "animation", "context API"],
      text: "Vision board application that has the default vision board view and individual goals/visions with details when flipped over .",
      github: "https://github.com/faithandjs/vivienne-daniels-store",
      live: "https://vision-board-2023.netlify.app/",
      target: "_blank",
    },
    {
      id: 3,
      name: "Reward.io",
      img: "reward-io.webp",
      tags: ["Vue", "typescript", "Desktop only"],
      text: "Crypto reward website. It is a single page application created with Vue js",
      github: "https://github.com/faithandjs/reward.io",
      live: "https://reward-io.netlify.app/",
      target: "_blank",
    },
    {
      id: 4,
      name: "Freebies--Coworking Space",
      img: "freebies.webp",
      tags: ["Gatsby JS", "typescript", "tailwindcss", "Desktop only"],
      text: "This a single page application created with Gatsby Js and Tailwind css",
      github:
        "https://github.com/faithandjs/Freebies---Coworking-Space-landing-page",
      live: "https://freebies-coworking-space.netlify.app/",
      target: "_blank",
    },
    {
      id: 5,
      name: "Rock, Paper, Scissors ( Lizard, Spork )",
      img: "rpsls.webp",
      tags: ["SASS", "React JS", "typescript", "Localstorage"],
      text: "This is adaptation of the Rock, Paper, Scissors game. Users can play against the computer by clicking the icons.",
      github: "https://github.com/faithandjs/rock-paper-scissors",
      live: "https://rock-paper-scissors-lizard-spock-fe.netlify.app/",
      target: "_blank",
    },
  ],
};
